### ISSUE TITLE
Run time error with MPICH3.3 on macbook

### ISSUE THREAD

**Issue by geyan3566** [japalmer29/amica#11]
Dear folks,
I was trying to install and run mpich3.3 on my mac. The compile I think it's ok. However, I got this runtime error:
_Fatal error in MPI_Init: Other MPI error, error stack:

[MPIR_Init_thread(565)..............: 
MPID_Init(224).....................: channel initialization failed
MPIDI_CH3_Init(105)................: 
MPID_nem_init(324).................: 
MPID_nem_tcp_init(178).............: 
MPID_nem_tcp_get_business_card(425): 
MPID_nem_tcp_init(384).............: gethostbyname failed, Mac (errno 1)](url)

Could anyone please help me point out the issue and inform me how to solve it?

**Comment by geyan3566** [comment]
Please ignore the "link" format of this error message.

**Comment by Sarm283** [comment]
Hello - I was just wondering how you solved this issue? I seem to be having the very same problem.
