### ISSUE TITLE
(Another) Reference to non-existent field 'W' error .... 

### ISSUE THREAD

**Issue by Sarm283** [japalmer29/amica#26]
Hi all,
It seems I am producing an error that has been reported and discussed a few times already. I have read through the previous posts (and suggested fixes), however I am unable to stop the error from occuring. I have included the readout from the MATLAB command below - could someone please help me with stopping this error. 

> MPIR_Init_thread(474)..............:
> MPID_Init(190).....................: channel initialization failed
> MPIDI_CH3_Init(89)................:
> MPID_nem_init(320).................:
> MPID_nem_tcp_init(173).............:
> MPID_nem_tcp_get_business_card(420):
> MPID_nem_tcp_init(384).............: gethostbyname failed, habs-hr-2zdv30 (errno 1)
> [unset]: write_line_error; fd=-1 buf:cmd=abort exitcode 3191311
> :
> system msg for write_line failure : Bad file descriptor
> Something went wrong...
> No gm  present, setting num_models to 1
> No W present, exiting**
> Reference to non-esistent field 'W'
> 
> Error in runamica15 (line 892)
>         weights = mods.w(:,:,1);
> 
> Error in pop_runica (line239)
>         [W,S,mods] = runamica15(datfile,arglist{:};
> 
> Error while evaluating Menu Callback

**Comment by japalmer29** [comment]
Hi Sam,

 

Can you post the script you are using? There might be some error in the way you are calling the amica function.

 

Jason

**Comment by Sarm283** [comment]
Hi Jason,

I am actually just trying to launch it using the EEGlab GUI… In any case, I have narrowed down why the error is happening….. For me to use MATLAB, I need to connect to the university VPN (licensing reasons)… when I disconnect from the VPN, there is a few minutes where I can use MATLAB before it closes. During this time AMICA works fine.

Any suggestions on how fix things so that I can use AMICA while connected to the VPN?

Cheers,

Sam

--
Sam Armstrong
M +614 24 449 609
E samuel.armstrong@uq.edu.au<mailto:samuel.armstrong@uq.edu.au>

**Comment by japalmer29** [comment]
Hmm, I’m not sure why it would be failing only when you use VPN. Maybe someone on EEGLAB list has had similar experience, so you might post a question there?

**Comment by Sarm283** [comment]
I fixed the issue – it did have something to do with the VPN, though I’m not precisely sure what it was. In any case, reinstalling MATLAB with a license that didn’t require an external connection stopped the error from reoccurring.



--
Sam Armstrong
M +614 24 449 609
E samuel.armstrong@uq.edu.au<mailto:samuel.armstrong@uq.edu.au>
