### ISSUE TITLE
question about random seed

### ISSUE THREAD

**Issue by skostrichegg** [japalmer29/amica#29]
Hi,

I would like to ask you a question about random seed of amICA.

amICA is calling random_seed with multiplication of system clock and some other values.
There doesn't seem to be a parameter to fix random seed.

Could you explain me why amICA uses random indexing?
And are there any expected problem with setting a fixed seed number of amICA?

ex) call random_seed(100)

Because I want to get the same results for all runs, if the inputs are same.

I'm waiting your reply,

Thank you.

**Comment by skostrichegg** [comment]
Hi,

I got a one more question.

As you had guided, I tested amICA after enabled 'fix_init',
then can check returns the same results by every run.

But weird thing is that all components are quite different from before enabled 'fix_init'.

And we tested with another time-series data,
all components are very similar with the result of the first time-series data, even if those two time-series data looks like different.

It doesn't seems to amICA analyze components of time-series well, if not using random function.

Could you explain me if there are any restrictions of enabling 'fix_init' ?


Thank you!

**Comment by japalmer29** [comment]
The starting point should not be that different so I’m not sure why it is working very differently, except that maybe with the fixed starting point it takes many more iterations. If the results are similar from two datasets, you may be looking at the sphering components near the starting point, which are similar for different datasets. If you increase max_iter to 10,000 it may converge to the non-fixed starting point solution.

 

Best,

Jason

**Comment by skostrichegg** [comment]
Thank you for response!

**Comment by leima1** [comment]
Hi @japalmer29 
 
I am also trying to get my results consistent after calling AMICA. I stumbled upon this post and tried changing 'fix_init' to 1. However when I run amica15() with fix_init to 1, I get the following warnings before it stops running:

```
 Matrix A(:,:,           1 ) is singular! 
           1 : block size =          128 
           1 : entering the main loop ... 
 model            1  determinant zero! 
...
 model            1  determinant zero! 
 iter     1 lrate =  0.0500000000 LL = ************** nd =  0.1301889110, D =  -0.88500E+05 -0.88500E+05  (  0.76 s,   0.4 h) 
 iter     2 lrate =  0.0500000000 LL =            NaN nd =           NaN, D =   0.00000E+00  0.00000E+00  (  0.17 s,   0.1 h) 
 Reinitializaing and starting over ... 
 iter     2 lrate =  0.0500000000 LL =            NaN nd =           NaN, D =   0.00000E+00  0.00000E+00  (  0.19 s,   0.1 h) 
 Reinitializaing and starting over ... 
 iter     2 lrate =  0.0500000000 LL =            NaN nd =           NaN, D =   0.00000E+00  0.00000E+00  (  0.18 s,   0.1 h) 
 Reinitializaing and starting over ... 
 iter     2 lrate =  0.0500000000 LL =            NaN nd =           NaN, D =   0.00000E+00  0.00000E+00  (  0.19 s,   0.1 h) 
 Reinitializaing and starting over ... 
 iter     2 lrate =  0.0500000000 LL =            NaN nd =           NaN, D =   0.00000E+00  0.00000E+00  (  0.19 s,   0.1 h) 
... done. Execution time:   0.00 h  
```

I have tried this in Windows 11 and Ubuntu 22.04.5.  I am using AMICA 1.7. Matlab 2023b, and eeglab 2025. 
amica15() runs completely fine on my dataset if I don't try to fix the init. I am hoping you can provide some insight or alternatives. 

Thank you,
Leo
