### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by co60ca** [japalmer29/amica#6]
Hey Jason,

We use Amica a lot over here at Brock University and I just wanted to thank you for you efforts.

Just was going through and was packaging some of your binaries and noticed you don't provide a license. GPL3 would be best or MIT. EEGLAB is LGPL so GPL might be a good fit anyway.

Thanks,

**Comment by palday** [comment]
@japalmer29 bump on this.

**Comment by co60ca** [comment]
Hi from 3 years in the future, maybe an email would be a good idea haha

**Comment by japalmer29** [comment]
Amica is included with EEGLAB. So the license is the same as that for
EEGLAB. rhe Python library MNE I think is BSD and there seems to be a
limiting conflict. Currently there is no solution to this issue.

Jason

**Comment by palday** [comment]
Since this hosted in a different repository, it would be great to have a license notice here. Also note that the copyright holder can issue multiple licenses -- so having both a GPL and a BSD license would be possible. Also licensing AMICA under only BSD or MIT would still allow bundling in a GPL package like EEGLAB.

**Comment by arnodelorme** [comment]
EEGLAB is BSD not GPL. Also even if it was GPL the bundling would be possible.

**Comment by palday** [comment]
Ah, yes, I missed the [license change](https://github.com/sccn/eeglab/commit/d0f39c228b2d8fd4812ecd18d2bc2811bb27c27b#diff-e762034b1dd691f7e394d7803f96342f041f00008901f387b7079e981a492564), but I did say bundling would be possible. 

Nonetheless, an explicit declaration of the AMICA license in the AMICA repository would be great, even at the level of "This source file is part of EEGLAB".

**Comment by co60ca** [comment]
Copy it over into `LICENSE` ? I'd submit a pull request but I don't know who the copyright holder technically is.

```
Copyright <YEAR> <COPYRIGHT HOLDER>

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
THE POSSIBILITY OF SUCH DAMAGE.
```

**Comment by japalmer29** [comment]
Oh, I guess there was a change I forgot about from the original license.

 

I’m not sure if I am the copyright holder, or if there are restrictions from UCSD.

 

I am fine with adding the BSD license statement.

 

Arno, could you or one of the other contributors add the license statement?

 

Thanks,

Jason

**Comment by ericphanson** [comment]
Bump :)

**Comment by japalmer29** [comment]
Sorry for the lack of clarity on license. Amica is released under BSD
license, like eeglab.

**Comment by jadonogh** [comment]
Bump :)

**Comment by jadonogh** [comment]
Bump :), hopefully Phillip’s pr closes it! @arnodelorme @japalmer29

**Comment by arnodelorme** [comment]
I will leave it up to Jason. Jason you can accept the pull request if you agree with the BSD license terms.

**Comment by japalmer29** [comment]
Sorry I thought this was done already. I merged the pr.

 

Jason
